In [26]:
 import numpy as np

 # **Basic Array Creation**

In [27]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [28]:
a = [1,2,6,7]
a

[1, 2, 6, 7]

list can store multiple data type but array can store only one data type 

In [29]:
b = [1,3,4,6.9,'hello']
b

[1, 3, 4, 6.9, 'hello']

Now if you convert this list into a array then due to string present into the list all element of list converted into string

In [30]:
np.array(b)

array(['1', '3', '4', '6.9', 'hello'], dtype='<U32')

In [31]:
c = [1,2,3,4.2]
c 

[1, 2, 3, 4.2]

If the present element is float then it convert all the elements into float datatype

In [32]:
np.array(c)

array([1. , 2. , 3. , 4.2])

In [33]:
l =[[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [34]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# **Array Genration Function**

**Range Function**  

Syntax : np.arange(Start, end, step)

In [35]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

we can genrate some zero's

In [36]:
arr = np.zeros(4)
arr

array([0., 0., 0., 0.])

It is a one dimenstional if you want to genrate a matrix of zero then

Syntax: np.zeros((m,n))

In [37]:
arr = np.zeros((4,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

If you want a matrix of 1 then

In [38]:
arr = np.ones(5)
arr

array([1., 1., 1., 1., 1.])

In [39]:
arr= np.ones((4,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [25]:
arr = np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

# **Random Generation Function**

If you want to genrate some random numbers

It is a vector and values are between 0 and 1. It is a concept of normalization

In [41]:
np.random.rand(10)

array([0.50021154, 0.36106732, 0.87594455, 0.17198821, 0.40032015,
       0.7327135 , 0.05071285, 0.10993705, 0.48999719, 0.40934161])

It is vector and values are between -3 to 3. It is a concept of Standardization. 
for that you need to use "np.random.randn()"

In [43]:
np.random.randn(10)

array([ 0.10700806, -0.62118094,  1.09803881,  0.45278677, -0.58536159,
        0.84452566, -0.02384368, -0.63726958, -0.69275516, -2.15376515])

If you want to genrate random integer then

In [44]:
np.random.randint(8)

3

If you provide sinle value in randint(), it genrate single value between 1 to that number.

Now if you want to genrate multiple random numbers then
np.random.randint(low, high, size)

In [46]:
np.random.randint(10,25,10)

array([15, 12, 10, 13, 18, 18, 24, 24, 24, 18], dtype=int32)

# **Array Attributes**

In [48]:
ar = np.array([[1,2,3],[7,8,9],[4,5,6]])
ar

array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])

In [49]:
ar.shape

(3, 3)

In [50]:
ar.size

9

In [51]:
ar.dtype

dtype('int64')

# **Array Methods**

In [52]:
ar

array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])

In [53]:
ar.min()

np.int64(1)

In [54]:
ar.max()

np.int64(9)

In [55]:
ar.sum()

np.int64(45)

In [57]:
np.sum(ar, axis = 0)

array([12, 15, 18])

In [58]:
np.sum(ar, axis = 1)

array([ 6, 24, 15])

In [59]:
ar.mean()

np.float64(5.0)

In [60]:
ar.std()

np.float64(2.581988897471611)

In [61]:
ar.argmin()

np.int64(0)

In [62]:
ar.argmax()

np.int64(5)

# **Reshaping and resizing**

In [64]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [65]:
arr = arr.reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])